layerrule = blur on,match:namespace match:namespace quickshell

layerrule = blur on,match:namespace ZShell-Bar
layerrule = blur_popups on,match:namespace ZShell-Bar
layerrule = ignore_alpha 0.5,match:namespace ZShell-Bar

layerrule = blur on,match:namespace ZShell-Auth
layerrule = blur_popups on,match:namespace ZShell-Auth
layerrule = ignore_alpha 0.6,match:namespace ZShell-Auth
