# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

exec-once = uwsm app -S out -- zshell-cli shell start

exec-once = [workspace 1] sleep 3s && uwsm app -S out -- discord --enable-features=WaylandLinuxDrmSyncobj
exec-once = [workspace 3 silent] sleep 3s && uwsm app -S out -- openrgb -p green --gui
exec-once = [workspace 2 silent] sleep 3s && uwsm app -S out -- keepassxc
# exec-once = [workspace 1 silent] sleep 3s && uwsm app -S out -- 64gram-desktop
exec-once = [workspace 1 silent] sleep 3s && uwsm app -S out -- AyuGram
exec-once = [workspace 3 silent] sleep 3s && uwsm app -S out -- solaar -b symbolic
exec-once = [workspace 2 silent] sleep 3s && uwsm app -S out -- librewolf
exec-once = uwsm app -S out -- kbuildsycoca6

# Load GTK settings
exec-once = uwsm app -S out -- ~/.config/hypr/scripts/gtk.sh

# Load cliphist history
exec-once = uwsm app -S out -- wl-paste --watch cliphist store
